#!/bin/bash             
#                       
# autoinstall - 31/07/2010 
#                       
# DebPBX-1.3.1        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
#                                                   
############################### START VARIABLES #######################################
#
clear
cat /var/www/pub/debpbx/debpbx
echo "Author: Federico Pereira <fpereira@opentecnologic.com>"
echo "Copyright 2009 - Federico Pereira (LordBasex)"
echo "This Distro is licensed under GNU/GPL version 2.0"
echo "Web Site: www.debpbx.org"
echo ""
echo ""
sleep 8;

#VARIABLES
VER_VERSION="1.3.1";                                                                                                
VER_ASTERISK="1.4.29";                                         
VER_ADDONS="1.4.10";                                                                                              
VER_DAHDI_COMPLETE="2.2.1.1+2.2.1.1"
VER_LIBPRI="1.4.10.2";                                                                                          
VER_FREEPBX="2.7.0";                                                                                                
VER_SPANDSP="0.0.6pre12";
VER_AVANTFAX="3.1.6";
VER_VTIGERCRM="5.1.0";  
                                                                                                                 
#DATA_BASE
ASTERISK_DB="asterisk_db";
AVANTFAX_DB="avantfax_db";
VTIGERCRM_DB="vtigercrm_db";

#USER_DATA
ASTERISK_USER="asterisk_us";
AVANTFAX_USER="avantfax_us";
VTIGERCRM_USER="vtigercrm_us";

#MANAGER
AMPMGR_USER="admin_mgr";

#HOST
HOSTS="pbx";
HOSTNAME="youdomain";
HOST_AND_HOSTNAME="${HOSTS}.${HOSTNAME}";

#MAIL
MAIL="you@mail";

#PORT
SSHPORT="22";

#USERS_DEFOUT_WU
ARI_ADMIN_USERNAME="debpbx";
FREEPBX_USER_WU="admin";
AVANTFAX_USER_WU="admin";
VTIGERCRM_USER_WU="admin";

export DEBIAN_FRONTEND="noninteractive";

#AUTO_DETECT_KERNEL
KERNEL_VERSION=`uname -r`
KERNEL_VERSION=`echo ${KERNEL_VERSION} | sed -e "s/\-\(.*\)//"`
KERNEL_UP_VERSION=`echo ${KERNEL_VERSION} | sed -e "s/\(2\.[4,6]\)\(.*\)/\1/"`

#IP_ADRESS
IP_ADRESS=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

#VERSION
echo "${VER_VERSION}" > /etc/debpbx_version

#RANDOMLY_GENERATED_PASSWORDS
MYSQL_ROOT_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
ASTERISK_DB_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
ASTERISK_MGR_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20` 
FREEPBX_ADMIN_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
FREEPBX_ADMIN_PW_SHA1=`echo -n "${FREEPBX_ADMIN_PW}" | sha1sum | awk '{ print $1 }'`
ARI_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20` 
FOP_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
AVANTFAX_DB_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
AVANTFAX_IAX_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
AVANTFAX_ADMIN_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 8`
AVANTFAX_ADMIN_PW_MD5=`echo -n "${AVANTFAX_ADMIN_PW}" | md5sum | awk '{ print $1 }'`
VTIGERCRM_DB_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
VTIGERCRM_MGR_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
VTIGERCRM_GENKEY=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 32`
############################### END VARIABLES #######################################

#INSTALATION LOG
LOG=/var/log/dp-install
#
echo -e "#\n# autoinstall - 10/04/2010\n#\n# DebPBX-$VER_VERSION\n# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>\n# Copyright 2008 Federico Pereira (LordBaseX)\n# This script is licensed under GNU GPL version 2.0\n#\n#" >> $LOG
echo "# VARIABLES" >> $LOG 
echo "# DebPBX VERSION: ${VER_VERSION}"  >> $LOG
echo "# ASTERISK VERSION: ${VER_ASTERISK}" >> $LOG 
echo "# ASTERISK ADDONS VERSION: ${VER_ADDONS}" >> $LOG
echo "# DAHDI_COMPLETE VERSION: ${VER_DAHDI_COMPLETE}" >> $LOG
echo "# LIBPRI VERSION: ${VER_LIBPRI}" >> $LOG
echo "# FREEPBX VERSION: ${VER_FREEPBX}" >> $LOG
echo "# SPANDSP VERSION: ${VER_SPANDSP}" >> $LOG
echo "# AVANTFAX VERSION: ${VER_AVANTFAX}" >> $LOG
echo "# VTIGERCRM VERSION: ${VER_VTIGERCRM}" >> $LOG
echo "# A2BILLING VERSION: ${VER_A2BILLING}" >> $LOG
echo "" >> $LOG
echo "# PBX HOSTNAME" >> $LOG
echo "# HOSTNAME: ${HOST_AND_HOSTNAME}" >> $LOG
echo "" >> $LOG
echo "# SSH PORT" >> $LOG
echo "# PORT: ${SSHPORT}" >> $LOG
echo "" >> $LOG
echo "# INTERFACE ETHERNET" >> $LOG
for INTERFACES in `/sbin/ifconfig | grep -i "eth" |  cut -c1-4` ;
do
    CON=$(($CON+1))
    ARRAY_IP_ADRESS[$CON]=`ifconfig $INTERFACES | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
    echo "# $INTERFACES: ${ARRAY_IP_ADRESS[$CON]}" >> $LOG
done
echo "" >> $LOG
echo "# KERNEL" >> $LOG
echo "# KERNEL: `uname -r`" >> $LOG
echo "" >> $LOG
echo "# CREATING PASSWORKS FILE WITH THE SYSTEM... FILE=/root/passwords" >> $LOG
echo "# RANDOMLY GENERATED PASSWORDS" > /root/passwords 
echo "" >> /root/passwords | tail -n 1 /root/passwords >> $LOG
echo "# MYSQL ROOT PASSWORD" >> /root/passwords
echo "MYSQL_ROOT_PW=\"${MYSQL_ROOT_PW}\";" >> /root/passwords 
echo "" >> /root/passwords
echo "# ASTERISK" >> /root/passwords
echo "ASTERISK_USER=\"${ASTERISK_USER}\";" >> /root/passwords
echo "ASTERISK_DB=\"${ASTERISK_DB}\";" >> /root/passwords
echo "ASTERISK_DB_PW=\"${ASTERISK_DB_PW}\";" >> /root/passwords 
echo "" >> /root/passwords
echo "# ASTERISK MANAGER INTERFACE (AMI)" >> /root/passwords
echo "AMPMGR_USER=\"${AMPMGR_USER}\";" >> /root/passwords
echo "ASTERISK_MGR_PW=\"${ASTERISK_MGR_PW}\";" >> /root/passwords 
echo "" >> /root/passwords
echo "# FLASH OPERATOR PANEL" >> /root/passwords
echo "FOP_PW=\"${FOP_PW}\";" >> /root/passwords 
echo "" >> /root/passwords
echo "# ARI" >> /root/passwords
echo "ARI_ADMIN_USERNAME=\"${ARI_ADMIN_USERNAME}\";" >> /root/passwords
echo "ARI_ADMIN_PASSWORD=\"${ARI_PW}\";" >> /root/passwords
echo "" >> /root/passwords
echo "# FREEPBX" >> /root/passwords
echo "FREEPBX_USER_WU=\"${FREEPBX_USER_WU}\";" >> /root/passwords
echo "FREEPBX_ADMIN_PW=\"${FREEPBX_ADMIN_PW}\";" >> /root/passwords
echo "FREEPBX_ADMIN_PW_SHA1=\"${FREEPBX_ADMIN_PW_SHA1}\";" >> /root/passwords
echo "" >> /root/passwords
echo "# AVANTFAX" >> /root/passwords
echo "AVANTFAX_USER=\"${AVANTFAX_USER}\";" >> /root/passwords
echo "AVANTFAX_DB=\"${AVANTFAX_DB}\";" >> /root/passwords
echo "AVANTFAX_DB_PW=\"${AVANTFAX_DB_PW}\";" >> /root/passwords
echo "AVANTFAX_IAX_PW=\"${AVANTFAX_IAX_PW}\";" >> /root/passwords
echo "AVANTFAX_USER_WU=\"${AVANTFAX_USER_WU}\";" >> /root/passwords
echo "AVANTFAX_ADMIN_PW=\"${AVANTFAX_ADMIN_PW}\";" >> /root/passwords
echo "AVANTFAX_ADMIN_PW_MD5=\"${AVANTFAX_ADMIN_PW_MD5}\";" >> /root/passwords
echo "" >> /root/passwords
echo "# VTIGERCRM" >> /root/passwords
echo "VTIGERCRM_USER=\"${VTIGERCRM_USER}\";" >> /root/passwords
echo "VTIGERCRM_DB=\"${VTIGERCRM_DB}\";" >> /root/passwords
echo "VTIGERCRM_DB_PW=\"${VTIGERCRM_DB_PW}\";" >> /root/passwords
echo "VTIGERCRM_MGR_PW=\"${VTIGERCRM_MGR_PW}\";" >> /root/passwords
echo "VTIGERCRM_GENKEY=\"${VTIGERCRM_GENKEY}\";" >> /root/passwords
echo "" >> $LOG
clear
echo "##################################################################" 
echo "# PARTE 1 - PREPARING INSTALLATION                               #" 
echo "##################################################################" 

rm /etc/apt/sources.list
touch /etc/apt/sources.list

echo "
deb http://ftp.us.debian.org/debian/ lenny main non-free contrib
deb-src http://ftp.us.debian.org/debian/ lenny main non-free contrib

deb http://security.debian.org/ lenny/updates main contrib non-free
deb-src http://security.debian.org/ lenny/updates main contrib non-free

deb http://volatile.debian.org/debian-volatile lenny/volatile main contrib non-free
deb-src http://volatile.debian.org/debian-volatile lenny/volatile main contrib non-free

deb http://oktan.ls.fi.upm.es/debian-multimedia/ stable main
deb-src http://oktan.ls.fi.upm.es/debian-multimedia/ stable main
" >> /etc/apt/sources.list

wget http://oktan.ls.fi.upm.es/debian-multimedia/pool/main/d/debian-multimedia-keyring/debian-multimedia-keyring_2008.10.16_all.deb -O  /var/cache/apt/archives/debian-multimedia-keyring_2008.10.16_all.deb    

dpkg -i /var/cache/apt/archives/debian-multimedia-keyring_2008.10.16_all.deb

aptitude update
aptitude -y safe-upgrade

aptitude update
aptitude -y install dpkg-dev grub2 startupmanager grub2-splashimages desktop-base
upgrade-from-grub-legacy
update-grub

aptitude -y install linux-source-$KERNEL_VERSION kernel-package g++ libncurses5-dev linux-libc-dev sqlite libnewt-dev libusb-dev zlib1g-dev libmysqlclient15-dev libsqlite0-dev loco mc unzip zip iptraf nmap screen subversion libqt4-core libqt4-gui ntpdate tcpdump libiksemel-dev libtiff4-dev libxml2-dev bison libaudiofile-dev                 

aptitude install -y linux-headers-`uname -r` build-essential hylafax-server iaxmodem bind9 postfix ghostscript netpbm libungif4-dev sudo cups expect libmagic-dev cmake vim-full

aptitude install -y apache2 php5 php5-common php5-cli mysql-server-5.0 php-pear php5-mysql php-db libapache2-mod-php5 php5-gd php5-curl libapache2-mod-perl2 php5-dev php5-ldap php5-mhash php5-odbc php5-mcrypt curl libwww-perl php5-imap python-setuptools python-mysqldb python-sqlalchemy python-psycopg2 imagemagick phpmyadmin mpg123 sox lame libmad0 libmad0-dev

aptitude install -y apache2-mpm-prefork apache2-utils apache2.2-common libapr1 libaprutil1 libsqlite3-0 libnetpbm10-dev libungif-bin php-mail php-mail-mime php-file psutils wdiff rsync atftpd libgnutls-dev libogg-dev                           

echo ""
echo "# DECOMPRESSING SOURCES KERNEL..."
cd /usr/src/ 
tar xjf linux-source-${KERNEL_VERSION}.tar.bz2
ln -s /usr/src/linux-source-${KERNEL_VERSION} /usr/src/linux
ln -s /lib/modules/${KERNEL_VERSION}/ /lib/modules/`uname -r`/asterisk

echo ""
echo "RECONFIGURATION LOCALE"
sed -i "s/# es_AR.UTF-8 UTF-8/es_AR.UTF-8 UTF-8/g" "/etc/locale.gen"
sed -i "s/# es_AR ISO-8859-1/es_AR ISO-8859-1/g" "/etc/locale.gen"
sed -i "s/# es_ES ISO-8859-1/es_ES ISO-8859-1/g" "/etc/locale.gen"
sed -i "s/# es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/g" "/etc/locale.gen"
sed -i "s/# es_ES@euro ISO-8859-15/es_ES@euro ISO-8859-15/g" "/etc/locale.gen"
sed -i "s/# en_US ISO-8859-1/en_US ISO-8859-1/g" "/etc/locale.gen"
sed -i "s/# en_US.ISO-8859-15 ISO-8859-15/en_US.ISO-8859-15 ISO-8859-15/g" "/etc/locale.gen"
sed -i "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" "/etc/locale.gen"
sed -i "s/\(^\LANG=\)\(.*\)/\1es_AR.UTF-8 UTF-8/" /etc/default/locale
dpkg-reconfigure -f noninteractive locales

echo ""
echo "RECONFIGURATION MYSQL"
echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MYSQL_ROOT_PW}');" | mysql -u root

echo ""
echo "RECONFIGURATION HOSTS"
rm /etc/hosts
echo "
127.0.0.1 localhost.localdomain localhost
${IP_ADRESS} ${HOST_AND_HOSTNAME} ${HOSTS}         

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback                  
fe00::0 ip6-localnet                                      
ff00::0 ip6-mcastprefix                                   
ff02::1 ip6-allnodes                                      
ff02::2 ip6-allrouters                                    
ff02::3 ip6-allhosts                                      
" >> /etc/hosts                 

echo ${HOST_AND_HOSTNAME} > /etc/hostname
/etc/init.d/hostname.sh start       

echo ""
echo "RECONFIGURATION ALIASES"
echo "root: $MAIL" >> /etc/aliases
/usr/bin/newaliases

echo ""
echo "RECONFIGURATION SCREENRC"
cp /var/www/pub/debpbx/.screenrc /root/

echo ""
echo "RECONFIGURATION POASTERISK_DBSTFIX"
postconf -e "myhostname = ${HOST_AND_HOSTNAME}" 
postconf -e "mydestination = ${HOST_AND_HOSTNAME}, localhost.${HOSTNAME}, localhost.localdomain, localhost"
postconf -e "inet_protocols = all"                                                                   
postconf -e "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"                              
echo ${HOST_AND_HOSTNAME} > /etc/mailname                                                               
/etc/init.d/postfix restart                                                                

echo "RECONFIGURATION BIND9"
echo ""
#/etc/init.d/bind9 stop
#sed -i "s/\(^\OPTIONS=\)\(.*\)/\1\"-u bind -t \/var\/lib\/named\"/" /etc/default/bind9
#mkdir -p /var/lib/named/etc                                                           
#mkdir /var/lib/named/dev                                                              
#mkdir -p /var/lib/named/var/cache/bind                                                
#mkdir -p /var/lib/named/var/run/bind/run                                              
#mv /etc/bind /var/lib/named/etc                                                       
#ln -s /var/lib/named/etc/bind /etc/bind                                               
#mknod /var/lib/named/dev/null c 1 3                                                   
#mknod /var/lib/named/dev/random c 1 8                                                 
#chmod 666 /var/lib/named/dev/null /var/lib/named/dev/random                           
#chown -R bind:bind /var/lib/named/var/*                                               
#chown -R bind:bind /var/lib/named/etc/bind                                            

#echo "
#$AddUnixListenSocket /var/lib/named/dev/log
#">> /etc/rsyslog.d/bind-chroot.conf        

#sed -i "s/auth-nxdomain no/\/\/auth-nxdomain no/g" "/var/lib/named/etc/bind/named.conf.options"
#sed -i "s/listen-on-v6/\/\/listen-on-v6/g" "/var/lib/named/etc/bind/named.conf.options"        
#sed -i 's/listen-on-v6 { any; };/listen-on-v6 { any; };\n# linea1/' /var/lib/named/etc/bind/named.conf.options
#sed -i 's/# linea1/# linea1\n# linea2/' /var/lib/named/etc/bind/named.conf.options                            
#sed -i "s/# linea1/ listen-on-v6 { any; };/g" "/var/lib/named/etc/bind/named.conf.options"                    
#sed -i "s/# linea2/ listen-on { 127.0.0.1; };/g" "/var/lib/named/etc/bind/named.conf.options"                 

#rm /etc/resolv.conf
#touch /etc/resolv.conf
#echo nameserver 127.0.0.1 > /etc/resolv.conf
#/etc/init.d/bind9 start                     

#sed -i "s/#prepend domain-name-servers 127.0.0.1;/prepend domain-name-servers 127.0.0.1;/g" "/etc/dhcp3/dhclient.conf"
#sed -i "s/domain-name-servers,//g" "/etc/dhcp3/dhclient.conf"                                                         

echo ""
echo "EXTRACTING TEMPORARY FILES..."
cd /usr/src/
tar zxf /var/www/pub/telephony/asterisk/asterisk-${VER_ASTERISK}.tar.gz
tar zxf /var/www/pub/telephony/asterisk/asterisk-addons-${VER_ADDONS}.tar.gz
tar zxf /var/www/pub/telephony/libpri/libpri-${VER_LIBPRI}.tar.gz           
tar zxf /var/www/pub/telephony/dahdi-linux-complete/dahdi-linux-complete-${VER_DAHDI_COMPLETE}.tar.gz
tar zxf /var/www/pub/tools/freepbx-${VER_FREEPBX}.tar.gz                        
tar zxf /var/www/pub/tools/spandsp-${VER_SPANDSP}.tgz
tar zxf /var/www/pub/tools/avantfax-${VER_AVANTFAX}.tgz
tar zxf /var/www/pub/tools/iksemel-1.4.tar.gz
tar zxf /var/www/pub/tools/speex-1.2rc1.tar.gz                        

echo ""
echo "##################################################################"
echo "# PARTE 2 - ASTERISK INSTALLATION                                #"
echo "##################################################################"

echo ""
echo "COMPILER IKSEMEL"
# download, make and install XML library for Google Talk
cd /usr/src/
cd iksemel-*
./configure
make
make install
cd ..

echo "COMPILER SPEEX CODEC"
cd /usr/src/
cd speex-*
./configure
make
make install
cd ..

echo ""
echo "COMPILER DAHDI-LINUX-COMPLETE"
cd /usr/src/dahdi-linux-complete-${VER_DAHDI_COMPLETE}
make all && make install && make config

echo ""
echo "COMPILER LIBPRI"
cd /usr/src/libpri-${VER_LIBPRI}                                         
make && make install

echo ""
echo "COMPILER ASTERISK"
cd /usr/src/asterisk-${VER_ASTERISK}
./configure
make && make install && make samples 

echo ""
echo "COMPILER ASTERISK ADDONS"
cd /usr/src/asterisk-addons-${VER_ADDONS}
./configure                              
make && make install && make samples                             

echo ""
echo "COMPILER SPANDSP"
cd /usr/src/spandsp-*
./configure
make && make install

echo ""
echo "COMPILER AGX-AST-ADDONS"
cp -R /var/www/pub/tools/agx-ast-addon /usr/src
cd /usr/src
#BUG FIX
#REMOVE APP_CONFCALL FROM BUILD
echo "project (agx-ast-addons-zaptel)" >  agx-ast-addon/app-dahdi/CMakeLists.txt
echo >> agx-ast-addon/app-dahdi/CMakeLists.txt
cd /usr/src/agx-ast-addon
./configure.sh
./build.sh
cp /usr/src/agx-ast-addon/dist/*.so /usr/lib/asterisk/modules
chown -R root:root /usr/lib/asterisk/modules

echo ""
echo "PREPARING ASTERISK INSTALLATION"
#CREATE USER ASTERISK & GROUP
adduser asterisk --disabled-password --no-create-home --gecos "asterisk PBX user"
adduser www-data asterisk

#MODIFICATION ASTERISK                                                                                
cp /etc/asterisk/asterisk.conf /etc/asterisk/asterisk.conf.orig
sed -i "s/\(astrundir *=> *\)\(.*\)/\1\/var\/run\/asterisk/" /etc/asterisk/asterisk.conf
sed -i "s/\[directories\](!) .*/[directories]/" /etc/asterisk/asterisk.conf
sed -i '1 {s/\<sh\>/bash/}' /usr/sbin/safe_asterisk
mkdir /var/run/asterisk
chown asterisk:asterisk -R /var/run/asterisk
chown asterisk:asterisk -R /etc/asterisk
chown asterisk:asterisk -R /var/lib/asterisk
chown asterisk:asterisk -R /var/log/asterisk
chown asterisk:asterisk -R /var/spool/asterisk
chown asterisk:asterisk -R /var/www
chmod 770 /etc/asterisk/                
chmod 770 /var/lib/asterisk/  

echo ""
echo "SCRIPT INITIATION ASTERISK FILE=/etc/init.d/asterisk {start|stop|restart|force-reload}"
cp /var/www/pub/debpbx/asterisk /etc/init.d/asterisk
chmod +x /etc/init.d/asterisk
echo ""
echo "UPDATE SERVICES LOADING AT BOOT TIME..."
chmod 755 /etc/init.d/asterisk
update-rc.d asterisk defaults 90 10
###################################################################################################
###################################################################################################
###################################################################################################
clear
echo "##################################################################"
echo "# PARTE 2 - INSTALATION FREEPBX                                  #"
echo "##################################################################"

echo "CREATE DATABASE IF NOT EXISTS asteriskcdrdb;" | mysql -u root -p${MYSQL_ROOT_PW}
echo "CREATE DATABASE IF NOT EXISTS ${ASTERISK_DB};" | mysql -u root -p${MYSQL_ROOT_PW} 
echo "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO ${ASTERISK_USER}@localhost IDENTIFIED BY '${ASTERISK_DB_PW}';" | mysql -u root -p${MYSQL_ROOT_PW}
echo "GRANT ALL PRIVILEGES ON ${ASTERISK_DB}.* TO ${ASTERISK_USER}@localhost IDENTIFIED BY '${ASTERISK_DB_PW}';" | mysql -u root -p${MYSQL_ROOT_PW}  

sed -i "s/\(CREATE TABLE cdr\)/DROP TABLE IF EXISTS \`cdr\`;\n\1/" /usr/src/freepbx-${VER_FREEPBX}/SQL/cdr_mysql_table.sql
mysql -u${ASTERISK_USER} -p${ASTERISK_DB_PW} asteriskcdrdb < /usr/src/freepbx-${VER_FREEPBX}/SQL/cdr_mysql_table.sql                    
mysql -u${ASTERISK_USER} -p${ASTERISK_DB_PW} ${ASTERISK_DB} < /usr/src/freepbx-${VER_FREEPBX}/SQL/newinstall.sql                              

echo ""
echo "FIX APACHE2"
cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf-orig
sed -i "s/\(^User *\)\(.*\)/\1asterisk/" /etc/apache2/apache2.conf
sed -i "s/\(^Group *\)\(.*\)/\1asterisk/" /etc/apache2/apache2.conf

echo ""
echo "FIX PHP5"
cp /etc/php5/apache2/php.ini /etc/php5/apache2/php.ini-orig
sed -e 's/upload_max_filesize = .*/upload_max_filesize = 128M/' /etc/php5/apache2/php.ini > /tmp/php.ini
cat /tmp/php.ini > /etc/php5/apache2/php.ini                                                            
sed -e 's/memory_limit = .*/memory_limit = 1100M/' /etc/php5/apache2/php.ini > /tmp/php.ini             
cat /tmp/php.ini > /etc/php5/apache2/php.ini                                                            
sed -i "s/\(magic_quotes_gpc *= *\)\(.*\)/\1Off/" /etc/php5/apache2/php.ini                             

echo ""
echo "CONFIGURE FREEPBX"
cp /usr/src/freepbx-${VER_FREEPBX}/install_amp /usr/src/freepbx-${VER_FREEPBX}/install_amp-orig
sed -i "s/\(^\$webroot*\)\(.*\)/\1 = \"\/var\/www\/html\";/" /usr/src/freepbx-${VER_FREEPBX}/install_amp
sed -i "s/xx.xx.xx.xx/${IP_ADRESS}/g" "/usr/src/freepbx-${VER_FREEPBX}/install_amp"                                          
chmod 755 /usr/src/freepbx-${VER_FREEPBX}/install_amp                                                                       
cd /usr/src/freepbx-${VER_FREEPBX}/   

echo ""
echo "CONFIGURE AMPORTAL"
cp /usr/src/freepbx-${VER_FREEPBX}/amportal.conf /etc/amportal.conf
chown asterisk:asterisk /etc/amportal.conf
sed -i "s/\(AMPDBHOST= *\)\(.*\)/\1localhost/" /etc/amportal.conf 
sed -i "s/# AMPDBUSER=asteriskuser/AMPDBUSER=${ASTERISK_USER} /g" "/etc/amportal.conf"
sed -i "s/# AMPDBPASS=amp109/AMPDBPASS=${ASTERISK_DB_PW}/g" "/etc/amportal.conf"
sed -i "s/\(AMPMGRUSER= *\)\(.*\)/\1${AMPMGR_USER}/" /etc/amportal.conf 
sed -i "s/\(AMPMGRPASS= *\)\(.*\)/\1${ASTERISK_MGR_PW}/" /etc/amportal.conf 
sed -i "s/AMPWEBADDRESS=/AMPWEBADDRESS=${IP_ADDRESS}/" /etc/amportal.conf
sed -i "s/\(FOPPASSWORD= *\)\(.*\)/\1${FOP_PW}/" /etc/amportal.conf
sed -i "s/\(ARI_ADMIN_USERNAME= *\)\(.*\)/\1${ARI_ADMIN_USERNAME}/" /etc/amportal.conf
sed -i "s/\(ARI_ADMIN_PASSWORD= *\)\(.*\)/\1${ARI_PW}/" /etc/amportal.conf
sed -i "s/\(AUTHTYPE *= *\)\(.*\)/\1database/" /etc/amportal.conf
sed -i "s/# ZAP2DAHDICOMPAT=true|false/ZAP2DAHDICOMPAT=true/g" "/etc/amportal.conf"
echo "AMPDBNAME=${ASTERISK_DB}" >> /etc/amportal.conf
echo "ASTETCDIR=/etc/asterisk" >> /etc/amportal.conf
echo "ASTMOconfigureDDIR=/usr/lib/asterisk/modules" >> /etc/amportal.conf 
echo "ASTVARLIBDIR=/var/lib/asterisk" >> /etc/amportal.conf
echo "ASTAGIDIR=/var/lib/asterisk/agi-bin" >> /etc/amportal.conf
echo "ASTSPOOLDIR=/var/spool/asterisk" >> /etc/amportal.conf
echo "ASTRUNDIR=/var/run/asterisk" >> /etc/amportal.conf
echo "ASTLOGDIR=/var/log/asterisk" >> /etc/amportal.conf
echo "AMPDEVUSER=asterisk" >> /etc/amportal.conf
echo "AMPDEVGROUP=asterisk" >> /etc/amportal.conf
echo "AMPASTERISKUSER=asterisk" >> /etc/amportal.conf
echo "AMPASTERISKGROUP=asterisk" >> /etc/amportal.conf
echo "AMPASTERISKWEBUSER=asterisk" >> /etc/amportal.conf
echo "AMPASTERISKWEBGROUP=asterisk" >> /etc/amportal.conf
echo "SSHPORT=${SSHPORT}" >> /etc/amportal.conf

echo ""
echo "INSTALATION FREEPBX"
./start_asterisk start
./install_amp --username=${ASTERISK_USER} --password=$ASTERISK_DB_PW  
./apply_conf.sh

echo ""
echo "CONFIGURE DAHDI"
cp /var/www/pub/debpbx/chan_dahdi.conf /etc/asterisk/chan_dahdi.conf
mv /etc/dahdi/genconf_parameters /etc/dahdi/genconf_parameters.bak
echo "context_lines          from-zaptel" > /etc/dahdi/genconf_parameters
modprobe dahdi_dummy

echo ""
echo "CONFIGURE FOP LANGUAGE SPANISH"
sed -i 's/language=en/language=es/' /var/www/html/panel/op_server.cfg
cp /var/www/html/admin/modules/dashboard/images/notify_* /var/www/html/admin/images/
ln -s /var/lib/asterisk/moh /var/lib/asterisk/mohmp3  

echo ""
echo "FREEPBX CUSTOMIZING SETTINGS & EXTENSION"
sed -i "s/FREEPBX_ADMIN/${FREEPBX_USER_WU}/g" "/var/www/pub/debpbx/myextension.sql"
sed -i "s/SHA1_PASS/${FREEPBX_ADMIN_PW_SHA1}/g" "/var/www/pub/debpbx/myextension.sql"
sed -i "s/IAX2_SECRET/${AVANTFAX_IAX_PW}/g" "/var/www/pub/debpbx/myextension.sql"
sed -i "s/E_MAIL/${MAIL}/g" "/var/www/pub/debpbx/myextension.sql"

mysql -u${ASTERISK_USER} -p${ASTERISK_DB_PW}  ${ASTERISK_DB} < /var/www/pub/debpbx/myextension.sql
###################################################################################################
###################################################################################################
###################################################################################################
clear
echo ""
echo "##################################################################"
echo "# PARTE 3 - AVANTFAX INSTALLATION                                #"
echo "##################################################################"

touch /etc/iaxmodem/ttyIAX         
touch /etc/hylafax/config.ttyIAX   
touch /etc/hylafax/FaxDispatch     
touch /etc/hylafax/config          
echo "calltokenoptional = 0.0.0.0/0.0.0.0" >> /etc/asterisk/iax_custom.conf

echo "
device /dev/ttyIAX
owner asterisk:asterisk
mode 660
port 45699
refresh 300
server 127.0.0.1
peername 400
secret ${AVANTFAX_IAX_PW}
cidname IAX Modem 1
cidnumber 400
codec slinear
" >> /etc/iaxmodem/ttyIAX

cp /var/www/pub/debpbx/config.ttyIAX /etc/hylafax/config.ttyIAX
                                   

mkdir -p /var/log/iaxmodem
echo "
iax0:2345:respawn:/usr/bin/iaxmodem ttyIAX&> /var/log/iaxmodem-ttyIAX
fax0:2345:respawn:/usr/sbin/faxgetty ttyIAX&> /var/log/faxgetty-ttyIAX
" >> /etc/inittab

echo "
FILETYPE=pdf;
SENDTO="$MAIL";
" >> /etc/hylafax/FaxDispatch

#configuracion
echo "#     
## AvantFAX configuration
#           configure             
NotifyCmd: bin/notify.php
#" >> /etc/hylafax/config 

echo "CoverCmd:		/var/www/html/avantfax/includes/faxcover.php" >> /etc/hylafax/sendfax.conf

#configuracion
echo "#
#
## JobFmt for AvantFAX
#
JobFmt: "%-3j %3i %1a %15o %40M %-12.12e %5P %5D %7z %.25s"
" >> /etc/hylafax/hyla.conf

#configuracion 
echo "#
## AvantFAX
#
FaxRcvdCmd:     bin/faxrcvd.php
DynamicConfig:  bin/dynconf.php
UseJobTSI:      true
" >> /etc/hylafax/config.ttyIAX

#SYNCING DIRECTORIES & FILE
/etc/init.d/hylafax restart

#RESET INITTAB
kill -HUP 1

#CONFIGURATION HOSTS.HFAXD
rm /etc/hylafax/hosts.hfaxd
echo "
# hosts.hfaxd
# This file contains permissions and password for every user in
# the system.
#
# For more information on this biject, please see its man page
# and the commands faxadduser and faxdeluser.
localhost:21:: 
127.0.0.1
" >> /etc/hylafax/hosts.hfaxd
/usr/sbin/faxadduser -a ${ASTERISK_DB_PW} asterisk
/etc/init.d/hylafax restart

#INSTALATION PACKAGES PEAR freepbx
pear channel-update pear.php.net
pear upgrade-all
pear install Mail Net_SMTP Mail_mime MDB2_driver_mysql fileinfo

cd /usr/src/avantfax-${VER_AVANTFAX}/
mv avantfax /var/www/html/avantfax
chown -R asterisk:asterisk /var/www/html/avantfax
chown -R asterisk.uucp /var/www/html/avantfax/tmp 
chown -R asterisk.uucp /var/www/html/avantfax/faxes

# CAMBIO DE PERMISOS A DIRECTORIOS
chmod -R 0770 /var/www/html/avantfax/tmp 
chmod -R 0770 /var/www/html/avantfax/faxes
chmod -R 0770 /var/www/html/avantfax/includes/templates/admin_theme/templates_c/
chmod -R 0770 /var/www/html/avantfax/includes/templates/admin_theme/cache/
chmod -R 0770 /var/www/html/avantfax/includes/templates/main_theme/templates_c/
chmod -R 0770 /var/www/html/avantfax/includes/templates/main_theme/cache/

# CAMBIO DE PERMISOS A ARCHIVOS
chmod 0755 /var/www/html/avantfax/includes/faxcover.php
chmod 0755 /var/www/html/avantfax/includes/faxrcvd.php
chmod 0755 /var/www/html/avantfax/includes/notify.php
chmod 0755 /var/www/html/avantfax/tools/update_contacts.php
chmod 0755 /var/www/html/avantfax/tools/faxcover.php
chmod 0755 /var/www/html/avantfax/includes/avantfaxcron.php
chmod 0755 /var/www/html/avantfax/includes/dynconf.php

# CAMBIO DE DUEÑO Y GRUPO
chown asterisk:asterisk /var/www/html/avantfax/includes/templates/admin_theme/templates_c/
chown asterisk:asterisk /var/www/html/avantfax/includes/templates/admin_theme/cache/
chown asterisk:asterisk /var/www/html/avantfax/includes/templates/main_theme/templates_c/
chown asterisk:asterisk /var/www/html/avantfax/includes/templates/main_theme/cache/

#CREATE USER MYSQL
echo "CREATE DATABASE IF NOT EXISTS ${AVANTFAX_DB};" | mysql -u root -p${MYSQL_ROOT_PW}
echo "GRANT ALL PRIVILEGES ON ${AVANTFAX_DB}.* TO ${AVANTFAX_USER}@localhost IDENTIFIED BY '${AVANTFAX_DB_PW}';" | mysql -u root -p${MYSQL_ROOT_PW}

sed -i "s/'admin'/'${AVANTFAX_USER_WU}'/g" "/usr/src/avantfax-${VER_AVANTFAX}/create_tables.sql"
sed -i "s/5f4dcc3b5aa765d61d8327deb882cf99/${AVANTFAX_ADMIN_PW_MD5}/g" "/usr/src/avantfax-${VER_AVANTFAX}/create_tables.sql"
sed -i "s/root@localhost/${MAIL}/g" "/usr/src/avantfax-${VER_AVANTFAX}/create_tables.sql"
mysql -u${AVANTFAX_USER} -p${AVANTFAX_DB_PW} ${AVANTFAX_DB} < /usr/src/avantfax-${VER_AVANTFAX}/create_tables.sql

#MOD
mv /usr/bin/faxcover /usr/bin/faxcover.old
ln -s /var/www/html/avantfax/includes/faxcover.php /usr/bin/faxcover
     
#SYMLINK AVANTFAX SCRIPTS
ln -s /var/www/html/avantfax/includes/faxrcvd.php /var/spool/hylafax/bin/faxrcvd.php
ln -s /var/www/html/avantfax/includes/dynconf.php /var/spool/hylafax/bin/dynconf.php
ln -s /var/www/html/avantfax/includes/notify.php  /var/spool/hylafax/bin/notify.php

#SETUP SUDO PERMISSIONS
cat /etc/sudoers | grep -v requiretty > /tmp/sudoers
echo "asterisk ALL= NOPASSWD: /sbin/reboot, /sbin/halt, /usr/sbin/faxdeluser, /usr/sbin/faxadduser -u * -p * *" >> /tmp/sudoers
mv /etc/sudoers /etc/sudoers.orig
mv /tmp/sudoers /etc/sudoers
chmod 0440 /etc/sudoers
chown root.root  /etc/sudoers

#MAKE BACKUP OF HYLAFAX CONFIGURATION
mkdir /etc/hylafax/abackup
cp /etc/hylafax/config* /etc/hylafax/abackup/

#CONFIGURE MODEMS TO USE AVANTFAX
echo "INSERT INTO \`FaxCategory\` (\`catid\`, \`name\`) VALUES(1, 'debpbx');
INSERT INTO \`Modems\` (\`devid\`, \`device\`, \`alias\`, \`contact\`, \`printer\`, \`faxcatid\`) VALUES(1, 'ttyIAX', 'Ventas', '', '', 1);
" >> /tmp/avantfax
mysql -u${AVANTFAX_USER} -p${AVANTFAX_DB_PW} ${AVANTFAX_DB} < /tmp/avantfax

#ADD CRONTAB ENTRIES
echo "Setting up /etc/cron.d/avantfax"
printf "0 * * * *\t/var/www/html/avantfax/includes/phb\n" >> /etc/cron.d/avantfax
printf "0 0 * * *\t/var/www/html/avantfax/includes/avantfaxcron.php -t 2\n" > /etc/cron.d/avantfax

#CONFIGURE LOCAL_CONFIG
cp /var/www/html/avantfax/includes/local_config-example.php /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(AFDB_USER', *\)\(.*\)/\1'${AVANTFAX_USER}');/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(AFDB_PASS', *\)\(.*\)/\1'${AVANTFAX_DB_PW}');/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(AFDB_NAME', *\)\(.*\)/\1'${AVANTFAX_DB}');/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(FAXRMPWD *\)\(.*\)/\1 = \"${ASTERISK_DB_PW}\";/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(FAXMAILUSER *\)\(.*\)/\1 = 'faxmaster';/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(WWWUSER *\)\(.*\)/\1 = 'asterisk';/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(ADMIN_EMAIL', *\)\(.*\)/\1'${MAIL}');/" /var/www/html/avantfax/includes/local_config.php
sed -i "s/\(dft_config_lang *\)\(.*\)/\1 = 'es';/" /var/www/html/avantfax/includes/local_config.php
chmod 444 /var/www/html/avantfax/includes/local_config.php
###################################################################################################
###################################################################################################
###################################################################################################
clear
echo "##################################################################"
echo "# PARTE 5 - Instalando vtiger CRM                                #"
echo "##################################################################"

echo "CREATE DATABASE ${VTIGERCRM_DB} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -p${MYSQL_ROOT_PW}
echo "GRANT ALL PRIVILEGES ON ${VTIGERCRM_DB}.* TO ${VTIGERCRM_USER}@localhost IDENTIFIED BY '${VTIGERCRM_DB_PW}';" | mysql -u root -p${MYSQL_ROOT_PW}

sed -i "s/DebPBX2009/${VTIGERCRM_MGR_PW}/g" "/var/www/pub/debpbx/vtigercrm/vtigercrm.sql"
mysql -u${VTIGERCRM_USER} -p${VTIGERCRM_DB_PW} ${VTIGERCRM_DB} < /var/www/pub/debpbx/vtigercrm/vtigercrm.sql 

cd /var/www/html
tar zxf /var/www/pub/tools/vtigercrm-${VER_VTIGERCRM}.tar.gz
cd /var/www/html/vtigercrm                                  

#Language
unzip -o /var/www/pub/debpbx/vtigercrm/Spanish_es_es_TSolucio_510GA.zip

#Cambiando permisos y dueño.
chmod 777 config.inc.php
chmod 777 tabdata.php   
chmod 777 install.php   
chmod 777 parent_tabdata.php
chmod -Rv 777 cache/        
chmod -Rv 777 storage/      
chmod -Rv 777 user_privileges/
chmod -Rv 777 Smarty/cache/   
chmod -Rv 777 Smarty/templates_c/
chmod -Rv 777 modules/Emails/templates/
chmod -Rv 777 modules/                 
chmod -Rv 777 cron/                    
chmod -Rv 777 test/contact/
chmod -Rv 777 test/vtlib/
chmod 777 backup/                      
chmod -Rv 777 Smarty/templates/modules/
chmod -Rv 777 test/wordtemplatedownload/
chmod -Rv 777 test/product/             
chmod -Rv 777 test/user/                
chmod -Rv 777 test/logo/                
chmod -Rv 777 logs/                     
chmod -Rv 777 install/  

sed -e 's/max_execution_time = .*/max_execution_time = 600/' /etc/php5/apache2/php.ini > /tmp/php.ini
cat /tmp/php.ini > /etc/php5/apache2/php.ini                                                         
sed -i "s/\(output_buffering *= *\)\(.*\)/\1On/" /etc/php5/apache2/php.ini                           
sed /etc/php5/apache2/php.ini -r -ibackup -f - <<END_SED_SCRIPT                                      
s/^error_reporting *=.*/error_reporting = E_WARNING \& \~E_NOTICE/;                                  
END_SED_SCRIPT

echo "
[crm] 
secret=${VTIGERCRM_MGR_PW}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
read=system,call,log,verbose,command,agent,user
write=system,call,log,verbose,command,agent,user
" >> /etc/asterisk/manager_custom.conf          

#REMOVE INSTALL
rm -rf /var/www/html/vtigercrm/install
rm /var/www/html/vtigercrm/install.php
rm /var/www/html/vtigercrm/migrate.php

cp /var/www/pub/debpbx/vtigercrm/config.inc.php /var/www/html/vtigercrm/config.inc.php
chmod 777 /var/www/html/vtigercrm/config.inc.php

#CONFIGURE CONFIG.INC.PHP
sed -i "s/USER_CRM/${VTIGERCRM_USER}/g" "/var/www/html/vtigercrm/config.inc.php"
sed -i "s/BASE_CRM/${VTIGERCRM_DB}/g" "/var/www/html/vtigercrm/config.inc.php"
sed -i "s/PASS_CRM/${VTIGERCRM_DB_PW}/g" "/var/www/html/vtigercrm/config.inc.php"
sed -i "s/dc66d1a8b837fd5771a6ce148834c0a6/${VTIGERCRM_GENKEY}/g" "/var/www/html/vtigercrm/config.inc.php"

cp /var/www/pub/debpbx/vtigercrm/parent_tabdata.php /var/www/html/vtigercrm/parent_tabdata.php
chmod 466 /var/www/html/vtigercrm/parent_tabdata.php

cp /var/www/pub/debpbx/vtigercrm/tabdata.php /var/www/html/vtigercrm/tabdata.php
chmod 466 /var/www/html/vtigercrm/tabdata.php

cp /var/www/pub/debpbx/vtigercrm/sharing_privileges_1.php /var/www/html/vtigercrm/user_privileges/sharing_privileges_1.php
cp /var/www/pub/debpbx/vtigercrm/sharing_privileges_2.php /var/www/html/vtigercrm/user_privileges/sharing_privileges_2.php
cp /var/www/pub/debpbx/vtigercrm/user_privileges_1.php /var/www/html/vtigercrm/user_privileges/user_privileges_1.php
cp /var/www/pub/debpbx/vtigercrm/user_privileges_2.php /var/www/html/vtigercrm/user_privileges/user_privileges_2.php

#INSTALATION MODULO PBXMANAGER
mkdir -p /tmp/vtigercrm
cd /tmp/vtigercrm      
unzip -o /var/www/html/vtigercrm/packages/5.1.0/mandatory/PBXManager.zip

mkdir -p /var/www/html/vtigercrm/cron/modules/PBXManager
cp -rf /tmp/vtigercrm/cron/ /var/www/html/vtigercrm/cron/modules/PBXManager                
chown -R asterisk:asterisk /var/www/html/vtigercrm/cron/modules/PBXManager
chmod -R 777 /var/www/html/vtigercrm/cron/modules/PBXManager

mkdir -p /var/www/html/vtigercrm/modules/PBXManager
cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/PBXManager
chmod -R 777 /var/www/html/vtigercrm/modules/PBXManager

mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/PBXManager
cp -rf  /tmp/vtigercrm/templates/EditView.tpl /var/www/html/vtigercrm/Smarty/templates/modules/PBXManager
cp -rf  /tmp/vtigercrm/templates/Settings.tpl /var/www/html/vtigercrm/Smarty/templates/modules/PBXManager
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/PBXManager
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/PBXManager
     
rm -fr /tmp/vtigercrm/cron
rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml

sed -i 's/"default"/"from-internal" /' /var/www/html/vtigercrm/modules/PBXManager/utils/AsteriskClass.php

#INSTALATION MODULO SERVICECONTRACTS 
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/mandatory/ServiceContracts.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/                       
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/ServiceContracts
chmod -R 777 /var/www/html/vtigercrm/modules/ServiceContracts

rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/manifest.xml   

#INSTALATION MODULO SERVICES
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/mandatory/Services.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/  
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/Services
chmod -R 777 /var/www/html/vtigercrm/modules/Services
           
rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/manifest.xml   

#INSTALATION MODULO CUSTOMERPORTAL  
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/optional/CustomerPortal.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/                    
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/CustomerPortal
chmod -R 777 /var/www/html/vtigercrm/modules/CustomerPortal

mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
cp -rf  /tmp/vtigercrm/templates/AdvancedSettingsContents.tpl /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
cp -rf  /tmp/vtigercrm/templates/AdvancedSettings.tpl /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
cp -rf  /tmp/vtigercrm/templates/BasicSetttingsContents.tpl /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
cp -rf  /tmp/vtigercrm/templates/BasicSetttings.tpl /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/CustomerPortal
   
rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml

#INSTALATION MODULO FIELDFORMULAS
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/optional/FieldFormulas.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/FieldFormulas       
chmod -R 777 /var/www/html/vtigercrm/modules/FieldFormulas

mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/FieldFormulas
cp -rf  /tmp/vtigercrm/templates/EditExpressions.tpl /var/www/html/vtigercrm/Smarty/templates/modules/FieldFormulas        
cp -rf  /tmp/vtigercrm/templates/ModuleTitle.tpl /var/www/html/vtigercrm/Smarty/templates/modules/FieldFormulas
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/FieldFormulas
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/FieldFormulas

rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml

#INSTALATION MODULO RECYCLEBIN
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/optional/RecycleBin.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/RecycleBin       
chmod -R 777 /var/www/html/vtigercrm/modules/RecycleBin
                
mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/RecycleBin
cp -rf  /tmp/vtigercrm/templates/RecycleBinContents.tpl /var/www/html/vtigercrm/Smarty/templates/modules/RecycleBin     
cp -rf  /tmp/vtigercrm/templates/RecycleBin.tpl /var/www/html/vtigercrm/Smarty/templates/modules/RecycleBin 
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/RecycleBin
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/RecycleBin

rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml

#INSTALATION MODULO TOOLTIP
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/optional/Tooltip.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/             
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/Tooltip
chmod -R 777 /var/www/html/vtigercrm/modules/Tooltip

mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
cp -rf  /tmp/vtigercrm/templates/default.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
cp -rf  /tmp/vtigercrm/templates/DetailQuickView.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
cp -rf  /tmp/vtigercrm/templates/EditQuickView.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
cp -rf  /tmp/vtigercrm/templates/Quickview.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/Tooltip

rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml                                                            

#INSTALATION MODULO WEBFORMS
cd /tmp/vtigercrm
unzip -o /var/www/html/vtigercrm/packages/5.1.0/optional/Webforms.zip

cp -rf /tmp/vtigercrm/modules/ /var/www/html/vtigercrm/              
chown -R asterisk:asterisk /var/www/html/vtigercrm/modules/Webforms
chmod -R 777 /var/www/html/vtigercrm/modules/Webforms

mkdir -p /var/www/html/vtigercrm/Smarty/templates/modules/Webforms
cp -rf  /tmp/vtigercrm/templates/ErrorPage.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Webforms  
cp -rf  /tmp/vtigercrm/templates/SuccessPage.tpl /var/www/html/vtigercrm/Smarty/templates/modules/Webforms
chown -R asterisk:asterisk /var/www/html/vtigercrm/Smarty/templates/modules/Webforms
chmod -R 777 /var/www/html/vtigercrm/Smarty/templates/modules/Webforms

rm -fr /tmp/vtigercrm/modules
rm -fr /tmp/vtigercrm/templates
rm -fr /tmp/vtigercrm/manifest.xml                                                        

#RECONFIGURATION OWNER AND GROUP
chown -R asterisk:asterisk /var/www/html/vtigercrm
###################################################################################################
###################################################################################################
###################################################################################################
clear
echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION APACHE2                                        |"
echo "+----------------------------------------------------------------+"
a2enmod ssl
a2enmod vhost_alias
cp /var/www/pub/debpbx/dynamicvhosting /etc/apache2/sites-available
cp -r /var/www/pub/debpbx/ssl /etc/apache2/
mkdir -p /var/www/www-virtuales
mkdir -p /var/www/www-virtualesssl
for IPADRESS in ${ARRAY_IP_ADRESS[@]}
do
      ln -s /var/www/html/ /var/www/www-virtuales/${IPADRESS}                       
      ln -s /var/www/html/ /var/www/www-virtualesssl/${IPADRESS}                                                                                   
done
chown asterisk:asterisk -R /var/www/www-virtuales
chown asterisk:asterisk -R /var/www/www-virtualesssl
a2dissite default
a2ensite dynamicvhosting
/etc/init.d/apache2 force-reload

echo "+----------------------------------------------------------------+"
echo "| INSTALATION PANEL DEBPBX                                       |"
echo "+----------------------------------------------------------------+"
cd /var/www/html/
rm /var/www/html/index.html
rm /var/www/html/mainstyle.css

cp -R /var/www/pub/debpbx/debpbx_panel/.svn/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/admin/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/includes/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/panel/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/skin/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/*.*  /var/www/html/
chown asterisk:asterisk -R /var/www/html/

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION PHPMYADMIN                                     |"
echo "+----------------------------------------------------------------+"
ln -s /usr/share/phpmyadmin/ /var/www/html/phpmyadmin
cd /etc/phpmyadmin/
sed '39a\$cfg['blowfish_secret'] ="asterisk";' config.inc.php > config.inc.tmp
mv config.inc.tmp config.inc.php

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION GRUB                                           |"
echo "+----------------------------------------------------------------+"
#cp /var/www/pub/debpbx/debpbx.tga /boot/grub/debpbx.tga                
#cp /boot/grub/debpbx.tga /usr/share/images/grub                        
#cp /boot/grub/debpbx.tga /usr/share/images/desktop-base/               
sed -i s/moreblue-orbit-grub/debpbx/g /etc/grub.d/05_debian_theme      
sed -i "s/\(color_normal*= *\)\(.*\)/\1white\/black/" /etc/grub.d/05_debian_theme
sed -i "s/\(color_highlight*= *\)\(.*\)/\1black\/white/" /etc/grub.d/05_debian_theme
sed -i s/OS=\"${GRUB_DISTRIBUTOR}/OS=\"DebPBX\ debpbx-${VER_VERSION}\ -\ ${GRUB_DISTRIBUTOR}/g /etc/grub.d/10_linux
update-grub                                                                                                        

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION GRUB                                           |"
echo "+----------------------------------------------------------------+"
echo "tftp            dgram   udp     wait    nobody  /usr/sbin/tcpd  /usr/sbin/in.tftpd /tftpboot" > /etc/inetd.conf
mkdir /tftpboot
chmod 777 /tftpboot

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION CRON                                           |"
echo "+----------------------------------------------------------------+"
echo "# m h  dom mon dow   command
0 * * * *   root  /usr/local/sbin/debpbx-update >> /dev/null 2>&1
" >>  /etc/cron.d/debpbx

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION BASH_LOGIN & BASHRC                            |"
echo "+----------------------------------------------------------------+"
cp /var/www/pub/debpbx/.bash_login /root/.bash_login                                                                
cp /var/www/pub/debpbx/.bashrc /root/.bashrc
echo "debpbx-settings"/root/.bashrc


echo "+----------------------------------------------------------------+"
echo "| INSTALATION COMMAND DEBPBX                                     |"
echo "+----------------------------------------------------------------+"
cp /var/www/pub/debpbx/script/debpbx-a2billing /usr/local/sbin/  
cp /var/www/pub/debpbx/script/debpbx-festival /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-help /usr/local/sbin/	    
cp /var/www/pub/debpbx/script/debpbx-pstn /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-update /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-chanskype /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-fop2 /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-password /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-siptosis /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-virtualhost /usr/local/sbin/
cp /var/www/pub/debpbx/script/debpbx-wizard /usr/local/sbin/
cd /var/www/pub/debpbx/script/
chmod +x debpbx-*

echo "+----------------------------------------------------------------+"
echo "| RECONFIGURATION OPEN-SSH-SERVER                                |"
echo "+----------------------------------------------------------------+"
mkdir /root/.ssh/
touch /root/.ssh/authorized_keys
sed -i "s/Port 22/Port ${SSHPORT}/" /etc/ssh/sshd_config
echo "Banner /etc/debpbx" >> /etc/ssh/sshd_config                                                                   
cp /var/www/pub/debpbx/debpbx /etc/debpbx                                                                           
/etc/init.d/ssh restart

clear
echo "+----------------------------------------------------------------+"
echo "|                   -  Instalation Succesfull -                  |"
echo "|                       http://www.debpbx.org                    |"
echo "+----------------------------------------------------------------+"
amportal restart
rm /etc/rc2.d/S99install
exit 0
