#!/bin/bash
#
# debpbx-pstn - 26/09/2010
#
# DebPBX-1.3.0
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)
# This script is licensed under GNU GPL version 2.0
#
#
#VARIABLE
source /etc/amportal.conf


function debpbx_dahdi_conf(){
 	/usr/sbin/amportal stop
	/usr/sbin/dahdi_genconf
	> /tmp/dahdi.txt
	/usr/sbin/dahdi_cfg -vvvvvv   | grep 'FX*' |  cut -d' ' -f3 | grep -o '[A-Z]*$' > /tmp/dahdi.txt
	CON_FXS=""
	CON_FXO=""
	for MODULES in `cat /tmp/dahdi.txt`
	do

        	if [ $MODULES != "FXO" ]; then
        	## CREATE TRUNK
        	        CON_FXS=$(($CON_FXS+1))
        	        #echo "$CON_FXS:$MODULES"
			CHANNELS=$CON_FXS
			#MYSQL INJECTION AND TRUNK EXTENSION
			echo "SELECT * FROM \`trunks\` WHERE \`trunkid\` ORDER BY trunkid DESC LIMIT 0,1;" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} | egrep -v "id" |  cut -f1 > /tmp/debpbx-pstn.tmp && ID_TRUNK=`cat /tmp/debpbx-pstn.tmp`
			ID_TRUNK=$(($ID_TRUNK+1))

			## BUILDING TRUNK FOR SKYPE SIP
			echo "INSERT INTO \`trunks\` (\`trunkid\`, \`name\`, \`tech\`, \`outcid\`, \`keepcid\`, \`maxchans\`, \`failscript\`, \`dialoutprefix\`, \`channelid\`, \`usercontext\`, \`provider\`, \`disabled\`) VALUES ($ID_TRUNK, 'DAHDI $CHANNELS', 'zap', '', 'off', '', '', '', '$CHANNELS', 'notneeded', '', 'off');" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME}
		
		## CREATE ZAPCHANDIDS
			echo "SELECT * FROM  \`zapchandids\` WHERE \`channel\` ORDER BY channel DESC LIMIT 0,1;" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} | egrep -v "id" |  cut -f1 > /tmp/debpbx-pstn2.tmp && ID_CHANNEL=`cat /tmp/debpbx-pstn2.tmp`
			ID_CHANNEL=$(($ID_CHANNEL+1))	
			echo "INSERT INTO \`zapchandids\` (\`channel\`, \`description\`, \`did\`) VALUES ($ID_CHANNEL, 'FXO $CHANNELS', '$CHANNELS-1');" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME}	

		elif [ $MODULES != "FXS" ]; then
	    		#CREATE EXTENSION  
	                CON_FXO=$(($CON_FXO+1))
	                
			#CHECK EXTENSION+1
			echo "SELECT * FROM  \`devices\` WHERE \`id\` ORDER BY id DESC LIMIT 0,1;" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} | egrep -v "id" |  cut -f1 > /tmp/debpbx-pstn3.tmp && EXTENSION=`cat /tmp/debpbx-pstn3.tmp`
			EXTENSION=$(($EXTENSION+1))

			echo "INSERT INTO \`zap\` (\`id\`, \`keyword\`, \`data\`, \`flags\`) VALUES
			('$EXTENSION', 'channel', '1', 0),
			('$EXTENSION', 'context', 'from-internal', 0),
			('$EXTENSION', 'immediate', 'no', 0),
			('$EXTENSION', 'signalling', 'fxo_ks', 0),
			('$EXTENSION', 'echocancel', 'yes', 0),
			('$EXTENSION', 'echocancelwhenbridged', 'no', 0),
			('$EXTENSION', 'echotraining', '800', 0),
			('$EXTENSION', 'busydetect', 'no', 0),
			('$EXTENSION', 'busycount', '7', 0),
			('$EXTENSION', 'callprogress', 'no', 0),
			('$EXTENSION', 'dial', 'ZAP/$CON_FXO', 0),
			('$EXTENSION', 'accountcode', '', 0),
			('$EXTENSION', 'callgroup', '', 0),
			('$EXTENSION', 'pickupgroup', '', 0),
			('$EXTENSION', 'mailbox', '$EXTENSION@device', 0),
			('$EXTENSION', 'account', '$EXTENSION', 0),
			('$EXTENSION', 'callerid', 'device <$EXTENSION>', 0),
			('$EXTENSION', 'record_in', 'Adhoc', 0),
			('$EXTENSION', 'record_out', 'Adhoc', 0);" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME}

			echo "INSERT INTO \`devices\` (\`id\`, \`tech\`, \`dial\`, \`devicetype\`, \`user\`, \`description\`, \`emergency_cid\`) VALUES ('$EXTENSION', 'zap', 'ZAP/$CON_FXO', 'fixed', '$EXTENSION', 'DAHDI $CON_FXO', '');" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME}

			"INSERT INTO \`users\` (\`extension\`, \`password\`, `name`, `voicemail`, `ringtimer`, `noanswer`, `recording`, `outboundcid`, `sipname`, `mohclass`) VALUES ('$EXTENSION', '', 'DAHDI $CON_FXO ', 'novm', 0, '', 'out=Adhoc|in=Adhoc', '', '', 'default');" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} 



	        fi

	done
}

function debpbx_reload(){
	#RELOAD CONFIG DAHDI AND AMPORTAL
        /etc/init.d/dahdi stop
        /etc/init.d/dahdi start
        /usr/sbin/amportal start
        asterisk -rx "dahdi show channels"

	#APPLY CONFIGURATION CHANGES
	echo "UPDATE \`asterisk_db\`.\`admin\` SET \`value\` = 'true' WHERE CONVERT( \`admin\`.\`variable\` USING utf8 ) = 'need_reload' LIMIT 1 ;" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME}
	/var/lib/asterisk/bin/module_admin reload
}
debpbx_dahdi_conf
debpbx_reload

