#!/bin/bash             
#                       
# debpbx- - 31/07/2010 
#                       
# DebPBX-1.3.0        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
#                                                   


for INTERFACES in `/sbin/ifconfig | grep -i "eth" |  cut -c1-4` ;
do
    CON=$(($CON+1))
    ARRAY_IP_ADRESS[$CON]=`ifconfig $INTERFACES | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
    ln -s /var/www/html/ /var/www/www-virtuales/${ARRAY_IP_ADRESS[$CON]}
    ln -s /var/www/html/ /var/www/www-virtualesssl/${ARRAY_IP_ADRESS[$CON]}
done
