#!/bin/bash             
#                       
# debpbx-pstn - 31/07/2010 
#                       
# DebPBX-1.3.0        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
echo ""
echo ""
echo ""
