#!/bin/bash             
#                       
# debpbx-siptosis - 15/11/2010 
#                       
# DebPBX-1.4       
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   

#VARIABLE
ID_TRUNK=""
EXTENSION=""
CPUINFO=`uname -a | grep 'amd64' | cut -d"-" -f3 | awk '{ print $1}'`
IP_ADRESS=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
source /etc/amportal.conf
data=$( tempfile 2>/dev/null )
trap "rm -f $data" 0 1 2 5 15

while [ 1 ]; do

dialog --backtitle "DebPBX - SipToSis - Part 1/4" --title "Enter User Name Skype" --inputbox "User Skype: " 8 60 2> $data
USER=`cat $data` 

	if [ "$(echo $USER)" != "" ]; then
		break;
	fi

done;

while [ 1 ]; do

# get password with the --insecure option
dialog --backtitle "DebPBX - SipToSis - Part 2/4"   --title "Password" \
--clear \
--insecure \
--passwordbox "Enter your password Skype" 10 35 2> $data
 
ret=$?

# make decison
case $ret in

  0)
    	PASS1=$(cat $data)
	;;
  1)
    	break;
	;;
  255)
 	[ -s $data ] &&  cat $data || echo "ESC pressed.";
	;;

esac


dialog --backtitle "DebPBX - SipToSis - Part 3/4"   --title "Password" \
--clear \
--insecure \
--passwordbox "Re enter your password Skype" 10 35 2> $data

ret=$?

# make decison
case $ret in

  0)
        PASS2=$(cat $data)
        ;;
  1)
        break;
        ;;
  255)
        [ -s $data ] &&  cat $data || echo "ESC pressed.";
        ;;

esac


if [ "$PASS1" == "$PASS2" ]; then
	break;
else
	dialog --title "Info" --clear --msgbox "The passwords are diferent, lets again!" 10 41
fi

done

PASS="$PASS1"


while [ 1 ]; do

dialog --backtitle "DebPBX - SipToSis - Part 4/4" --title "Enter Extension Number Incoming Route Skype" --inputbox "Extension Number: " 8 60 2> $data
EXTENSION=`cat $data`

        if [ "$(echo $EXTENSION | grep '^[0-9]')"  != "" ]; then
                break;
        fi

done;

chmod 777 /usr/src/siptosis/install
/usr/src/siptosis/install > /var/log/dp-siptosis
