#!/bin/bash
#                       
# debpbx-fop2 - 25/11/2010 
#                       
# DebPBX-1.4        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
#
#VARIABLES
FOP2_DB="fop2_db"; 
FOP2_USER="fop2_us";                                                                                                                                           FOP2_DB_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
data=$( tempfile 2>/dev/null )
trap "rm -f $data" 0 1 2 5 15

if [ -f /root/passwords ]
then                    
    source /root/passwords
else                                                     

    while [ 1 ]; do

	dialog --backtitle "DebPBX - FOP2" --title "Alert" --yesno "\nFop2 requires the mysql root password to install the databases. \n\nIf you don't rembember the password please get it, exit the script of installation and run it again. \n\nAnother option is to keep the file /root/password and run the script, the system will detect it and then will get the root password from this file. \n\nPress 'yes' to continue." 15 80
	sel=$?
	case $sel in
   	0) 
		;;
   	1) 
		exit; 
		;;
   	255) 
		;;
	esac

	# get password with the --insecure option
	dialog --backtitle "DebPBX - FOP2"   --title "Password" --clear --insecure --passwordbox "Enter your password Mysql root" 10 35 2> $data
 	ret=$?
	# make decison
	case $ret in
	  0)
    		PASS1=$(cat $data)
		;;
	  1)
    		exit;
		;;
  	255)
 		[ -s $data ] &&  cat $data || echo "ESC pressed.";
		;;
	esac


	dialog --backtitle "DebPBX - FOP2"   --title "Password" --clear --insecure --passwordbox "Re enter your password Mysql root" 10 35 2> $data
	ret=$?
	# make decison
	case $ret in
	  0)
        	PASS2=$(cat $data)
        	;;
	  1)
        	exit;
        	;;
  	255)
        	[ -s $data ] &&  cat $data || echo "ESC pressed.";
        	;;
	esac

	if [ "$PASS1" != "$PASS2" ]; then
		dialog  --backtitle "DebPBX - FOP2"  --title "Info" --clear --msgbox "The passwords are diferent, lets again!" 10 41
		continue;
	fi

	if [ "$PASS1" == "" ]; then
		dialog --backtitle "DebPBX - FOP2" --title "Info" --clear --msgbox "The passwords is empty, lets again!" 10 41
		continue;
	fi

        SQL_RESULT=`echo "show databases;" | mysql -u root -p${PASS1} 2>&1 | grep 'Access denied'`
	if [ "$SQL_RESULT" != "" ]; then
		dialog --title "Info" --clear --msgbox "The password is not valid!, lets again!" 10 41
		continue;
	fi
	MYSQL_ROOT_PW=$PASS1
	break;

     done

fi

clear
#INSTALATION & CONFIGURATION FOP2
echo "" >> /root/passwords 
echo "# FOP2" >> /root/passwords 
echo "FOP2_USER=\"${FOP2_USER}\";" >> /root/passwords 
echo "FOP2_DB=\"${FOP2_DB}\";" >> /root/passwords 
echo "FOP2_DB_PW=\"${FOP2_DB_PW}\";" >> /root/passwords 
source /etc/amportal.conf

cd /usr/src
if [ "$CPUINFO" == "amd64" ]; then
      wget http://debpbx.googlecode.com/svn/trunk/modules/fop2-2.11-debian-x86_64.tgz -O /usr/src/fop2-2.11-debian-x86_64.tgz
	
else
      wget http://debpbx.googlecode.com/svn/trunk/modules/fop2-2.11-debian-i386.tgz -O /usr/src/fop2-2.11-debian-i386.tgz
fi

cd /usr/src/
tar zxf /usr/src/fop2-2.11-debian-*.tgz

cd fop2
make install
cd /usr/local/fop2
cat extensions_override_freepbx.conf >> /etc/asterisk/extensions_override_freepbx.conf
echo "#extensions_override_freepbx.conf" >> /etc/asterisk/extensions_custom.conf

#AUTOCONFIG
sed -i "s/FROM asterisk/FROM asterisk_db/" /usr/local/fop2/autoconfig-buttons-freepbx.sh
sed -i "s/FROM asterisk/FROM asterisk_db/" /usr/local/fop2/autoconfig-users-freepbx.sh
chmod +x /usr/local/fop2/autoconfig-buttons-freepbx.sh
chmod +x /usr/local/fop2/autoconfig-users-freepbx.sh

#MANAGER
sed -i "s/\(manager_user= *\)\(.*\)/\1$AMPMGRUSER/" /usr/local/fop2/fop2.cfg
sed -i "s/\(manager_secret= *\)\(.*\)/\1$AMPMGRPASS/" /usr/local/fop2/fop2.cfg

#MOD FOP1
echo "" >> /var/www/html/panel/op_server.cfg
echo "#MOD LISTEN_PORT" >> /var/www/html/panel/op_server.cfg
echo "listen_port=4444" >> /var/www/html/panel/op_server.cfg

# VISUAL PHONEBOOK
sed -i "s/^\s*\$DBNAME\s*=\s*'.*'\s*;\s*/\$DBNAME = '$FOP2_DB';/g" /var/www/html/fop2/config.php
sed -i "s/^\s*\$DBUSER\s*=\s*'.*'\s*;\s*/\$DBUSER = '$FOP2_USER';/g" /var/www/html/fop2/config.php
sed -i "s/^\s*\$DBPASS\s*=\s*'.*'\s*;\s*/\$DBPASS = '$FOP2_DB_PW';/g" /var/www/html/fop2/config.php

echo "CREATE DATABASE IF NOT EXISTS $FOP2_DB;" | mysql -u root -p${MYSQL_ROOT_PW}
echo "GRANT ALL PRIVILEGES ON $FOP2_DB.* TO $FOP2_USER@localhost IDENTIFIED BY '$FOP2_DB_PW';" | mysql -u root -p${MYSQL_ROOT_PW}
sed -i "s/fop2/fop2_db/" /var/www/html/fop2/mysql.db
mysql -u$FOP2_USER -p$FOP2_DB_PW $FOP2_DB < /var/www/html/fop2/mysql.db

#RUM
echo "Restarting...."
/usr/local/fop2/autoconfig-buttons-freepbx.sh
/usr/local/fop2/autoconfig-users-freepbx.sh
/usr/local/sbin/amportal restart
/etc/init.d/fop2 start
exit 0
