#!/bin/bash
#
# debpbx-siptosis - 08/08/2010
#
# DebPBX-1.3.0
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)
# This script is licensed under GNU GPL version 2.0
#
#
#VARIABLES
ID_TRUNK=""
USER=""
PASS=""
EXTENSION=""
CPUINFO=`uname -a | grep 'amd64' | cut -d"-" -f3 | awk '{ print $1}'`
IP_ADRESS=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
source /etc/amportal.conf

clear
cat /etc/debpbx
echo "Author: Federico Pereira <fpereira@opentecnologic.com>"
echo "Copyright 2009 - Federico Pereira (LordBasex)"
echo "This Distro is licensed under GNU/GPL version 2.0"
echo "Web Site: www.debpbx.org"
echo ""
echo ""
echo "Se procederá a instalar la integración de Skype con DebPBX."
echo "Se necesitan los datos de la cuenta a configurar Skype,  usuario y clave."
echo "También se necesitará la extensión (interno) en donde entrará la llamada de Skype."
echo "Sino tiene una extensión cancele ésta instalación con control+z y cree el interno"
echo "y luego ejecute de nuevo éste comando: debpbx-siptosis"
echo ""
read -p "Usuario Skype: " USER
read -p "Clave: Skype:  " PASS
read -p "Extensión:     " EXTENSION
echo ""
key=""
while [ "$key" != "y" ] && [ "$key" != "n" ];do
	clear
	echo ""
	echo "+----------------------------------------------------------------+"
	echo "| CONFIRME QUE LOS DATOS SON CORRECTOS                           |"
	echo "+----------------------------------------------------------------+"
        echo ""
	echo "Usuario:   $USER"
	echo "Clave:     $PASS"
	echo "Extensión: $EXTENSION"
	echo ""
	read -n 1 -p "Confirme que los datos sean correctos [y/N]" key
done
echo ""
echo ""
if [ $key == "y" ]; then
	#INSTALACIÓN DE PAQUETES Y LIBRERIAS
	aptitude update
	aptitude -y install xserver-xorg-video-fbdev xterm libqt4-dev libxss-dev x11proto-scrnsaver-dev xvfb elinks tightvncserver blackbox 
        aptitude clean
	#VERIFICADOR DE CPU
	#architecture=$CPUINFO
	if [ "$CPUINFO" == "amd64" ]; then
		aptitude install ia32-libs ia32-libs-gtk libqt4-core libqt4-gui
		wget http://debpbx.googlecode.com/svn/trunk/modules/skype_2.1.0.81-1_amd64.deb  -O /usr/src/skype_2.1.0.81-1_amd64.deb
	dpkg -i /usr/src/skype_2.1.0.81-1_amd64.deb
	else
    		echo "deb http://download.skype.com/linux/repos/debian/ stable non-free" >>  /etc/apt/sources.list
    		apt-key adv --keyserver pgp.mit.edu --recv-keys 0xd66b746e
    		aptitude update && aptitude install skype
	fi

	aptitude -y install sun-java6-jdk

	#CREATE USER
	adduser stsuser --disabled-password --home /home/stsuser/ --gecos "stsuser SKYPE user" --force-badname
	adduser stsuser audio
	echo "stsuser:$PASS" | chpasswd --md5
	#SipToSis
	cp /var/www/pub/debpbx/modules/SipToSis_20100720.zip /usr/src/SipToSis_20100720.zip
	mkdir -p /home/stsuser/siptosis/
        cd /home/stsuser/siptosis/
	unzip /usr/src/SipToSis_20100720.zip
	chown stsuser:stsuser -R /home/stsuser/siptosis/
	cp /var/www/pub/debpbx/SkypeToSipAuth.props /home/stsuser/siptosis/SkypeToSipAuth.props
	sed -i "s/xx.xx.xx.xx/${IP_ADRESS}/g" "/home/stsuser/siptosis/SkypeToSipAuth.props"
	cp /var/www/pub/debpbx/stsTrunk_linux /home/stsuser/siptosis/stsTrunk_linux
	cp /home/stsuser/siptosis/stsTrunk_linux  /etc/init.d/siptosis
        chmod +x /etc/init.d/siptosis
	cp /home/stsuser/siptosis/samples/siptosis.cfg /home/stsuser/siptosis/siptosis.cfg
	chmod +x /home/stsuser/siptosis/stsTrunk_linux
	chmod +x /home/stsuser/siptosis/SipToSis_linux
	cp /var/www/pub/debpbx/rc.local /etc/rc.local



echo "

host_port=5070
contact_url=sip:123456789@127.0.0.1:5070
from_url=\"${USER}\" <sip:${USER}@127.0.0.1:5070>
username=${USER}
passwd=${PASS}
realm=127.0.0.1
" >> /home/stsuser/siptosis/siptosis.cfg

	#MYSQL INJECTION AND TRUNK EXTENSION
	echo "SELECT * FROM \`trunks\` WHERE \`trunkid\` ORDER BY trunkid DESC LIMIT 0,1;" | mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} | egrep -v "id" |  cut -f1 > /tmp/siptosip.tmp && ID_TRUNK=`cat /tmp/siptosip.tmp`
	ID_TRUNK=$(($ID_TRUNK+1))
	sed -i "s/IDXXX/${ID_TRUNK}/g" "/var/www/pub/debpbx/siptosis.sql"
	sed -i "s/USERXXX/${USER}/g" "/var/www/pub/debpbx/siptosis.sql"
	sed -i "s/PASSXXX/${PASS}/g" "/var/www/pub/debpbx/siptosis.sql"
	sed -i "s/EXTENSIONXXX/${EXTENSION}/g" "/var/www/pub/debpbx/siptosis.sql"
        mysql -u${AMPDBUSER} -p${AMPDBPASS} -D${AMPDBNAME} < /var/www/pub/debpbx/siptosis.sql
	echo ""
	echo ""
	echo "+----------------------------------------------------------------+"
	echo "| INSTALACION FINALIZADA CORRECTAMENTE                           |"
	echo "+----------------------------------------------------------------+"
        echo ""
	echo "Luego conectese con un cliente VNC para configurar su cuenta de Skype"
        echo "y acepte API skype4java a la ip: ${IP_ADRESS}:1"
        echo ""
        echo ""
        echo "Se procederá a reinicar el servidor en ... 8 segundo."
        echo "Si usted no quiere reiniciar presione control+z y reinícielo más tarde"
        echo "con el comando: shutdown -r now"
        sleep 8;
        shutdown -r now
else

	echo ""
	echo ""
	echo "Instalación abortada!!!"
	exit 1
fi
