#!/bin/bash             
#                       
# debpbx-update - 08/08/2010 
#                       
# DebPBX-1.3.0        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
#

svn update http://debpbx.googlecode.com/svn/trunk/ /var/www/pub/debpbx
cp /var/www/pub/debpbx/script/* /usr/local/sbin/
chmod -R 777 /usr/local/sbin/
cp -R /var/www/pub/debpbx/debpbx_panel/.svn/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/admin/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/images/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/includes/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/panel/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/skin/  /var/www/html/
cp -R /var/www/pub/debpbx/debpbx_panel/*.*  /var/www/html/
chown asterisk:asterisk -R /var/www/html/
echo "ACTUALIZACION REALIZADA"
