#!/bin/bash             
#                       
# debpbx-help - 31/07/2010 
#                       
# DebPBX-1.3.0        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
clear
echo "COMMAND TOOLS"
echo ""
echo "debpbx-a2billing - Autoinstall A2Bbilling."
echo "debpbx-chanskype - Autoinstall chan_skype."
echo "debpbx-pstn - Auto config pstn plates and clones such as Digium and Sangoma OpenVox."
echo "debpbx-siptosis - Autoinstall SipToSis of Skype integration through X and Java. (option GNU)"
echo "debpbx-password - Changer keys to the automated system. (Generates a new key file.)"
echo ""