#!/bin/bash
#
# debpbx-a2billing - 15/09/2010
#
# DebPBX-1.3.0
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)
# This script is licensed under GNU GPL version 2.0
#
#
#VARIABLES
VER_A2BILLING="1.7.1";
A2BILLING_DB="a2billing_db";
A2BILLING_USER="a2billing_us";
A2BILLING_MGR="a2billing_mgr";
A2BILLING_DB_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`
A2BILLING_MGR_PW=`head -c 200 /dev/urandom | tr -cd 'A-Za-z0-9' | head -c 20`



clear
cat /etc/debpbx
echo "Author: Federico Pereira <fpereira@opentecnologic.com>"
echo "Copyright 2009 - Federico Pereira (LordBasex)"
echo "This Distro is licensed under GNU/GPL version 2.0"
echo "Web Site: www.debpbx.org"
echo ""
echo ""
if [ -f /root/passwords ]
then
    source /root/passwords
else
    echo "It was detected that the file does not exist /root/passwords where is it?"
    echo "hosted the variable with the root password of MySQL"
    echo "Please enter the key manually or cancel pressing  control+c y"
    echo "re-copy the password file in the root folder"
    echo "and then run again debpbx-a2billing file"
    echo ""
    read -p "MySQL root password: " MYSQL_ROOT_PW

    MYSQL_SHOW_DATABASES=`echo "show databases;" | mysql -u root -p${MYSQL_ROOT_PW} 2>&1`
    MYSQL_SHOW_DATABASES=`echo "${MYSQL_SHOW_DATABASES}" | sed "s/\(.*\)\(Access denied\)\(.*\)/\2/"`
    if [ "${MYSQL_SHOW_DATABASES}" = "Access denied" ]; then
		echo "ERROR : passwords incorrect."
    exit 1;
    fi
fi

echo "" >> /root/passwords
echo "# A2BILLING" >> /root/passwords
echo "A2BILLING_USER=\"${A2BILLING_USER}\";" >> /root/passwords
echo "A2BILLING_DB=\"${A2BILLING_DB}\";" >> /root/passwords
echo "A2BILLING_DB_PW=\"${A2BILLING_DB_PW}\";" >> /root/passwords
echo "" >> $LOG

mkdir -p /usr/src/a2billing/
cd /usr/src/a2billing/
cp /var/www/pub/tools/A2Billing_${VER_A2BILLING}.tar.gz /usr/src/a2billing/A2Billing_${VER_A2BILLING}.tar.gz
tar xzf A2Billing_${VER_A2BILLING}.tar.gz

echo "create database ${A2BILLING_DB};" | mysql -u root -p${MYSQL_ROOT_PW}
echo "GRANT ALL PRIVILEGES ON ${A2BILLING_DB}.* TO ${A2BILLING_USER}@localhost IDENTIFIED BY '${A2BILLING_DB_PW}';" | mysql -u root -p${MYSQL_ROOT_PW}


sed -i "s/myasterisk/${A2BILLING_MGR}/g" "/usr/src/a2billing/DataBase/mysql-5.x/a2billing-schema-v1.4.0.sql"
sed -i "s/mycode/${A2BILLING_MGR_PW}/g" "/usr/src/a2billing/DataBase/mysql-5.x/a2billing-schema-v1.4.0.sql"
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/a2billing-schema-v1.4.0.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.0-to-v1.4.1.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.1-to-v1.4.2.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.2-to-v1.4.3.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.3-to-v1.4.4.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.4-to-v1.4.4.1.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.4.1-to-v1.4.5.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.4.5-to-v1.5.0.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.5.0-to-v1.5.1.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.5.1-to-v1.6.0.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.6.0-to-v1.6.1.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.6.1-to-v1.6.2.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1.6.2-to-v1.7.0.sql
mysql -uroot -p${MYSQL_ROOT_PW} ${A2BILLING_DB} </usr/src/a2billing/DataBase/mysql-5.x/UPDATE-a2billing-v1 .7.0-to-v1.7.1.sql

echo "+----------------------------------------------------------------+"
echo "| Configurando archivo a2billing.conf                            |"
echo "+----------------------------------------------------------------+"

cp /usr/src/a2billing/a2billing.conf /etc/
chown asterisk:asterisk /etc/a2billing.conf
sed -i "s/\(user *= *\)\(.*\)/\1${A2BILLING_USER}/" /etc/a2billing.conf
sed -i "s/\(password *= *\)\(.*\)/\1${A2BILLING_DB_PW}/" /etc/a2billing.conf
sed -i "s/\(dbname *= *\)\(.*\)/\1${A2BILLING_DB}/" /etc/a2billing.conf

echo "+----------------------------------------------------------------+"
echo "| web-based Graphical interfaces                                 |"
echo "+----------------------------------------------------------------+"
chmod 777 /etc/asterisk

mkdir /var/www/html/a2billing
touch /var/www/html/a2billing/index.html
chown asterisk:asterisk /var/www/html/a2billing

#new A2billing 1.7.1
mkdir -p /var/lib/a2billing/script
mkdir -p /var/run/a2billing

cp -rf /usr/src/a2billing/admin /var/www/html/a2billing
cp -rf /usr/src/a2billing/agent /var/www/html/a2billing
cp -rf /usr/src/a2billing/customer /var/www/html/a2billing
cp -rf /usr/src/a2billing/common /var/www/html/a2billing

#Fix the permissions of the templates_c folder in each of the UI
chmod 755 /var/www/html/a2billing/admin/templates_c
chmod 755 /var/www/html/a2billing/customer/templates_c
chmod 755 /var/www/html/a2billing/agent/templates_c

chown -Rf asterisk:asterisk /var/www/html/a2billing/admin/templates_c
chown -Rf asterisk:asterisk /var/www/html/a2billing/customer/templates_c
chown -Rf asterisk:asterisk /var/www/html/a2billing/agent/templates_c


echo "+----------------------------------------------------------------+"
echo "| Configure recurring services                                   |"
echo "+----------------------------------------------------------------+"

# Configure recurring services
mkdir /usr/lib/a2billing/
cp -rf /usr/src/a2billing/Cronjobs /usr/lib/a2billing/

echo "
# update the currency table
0 6 * * * php /usr/lib/a2billing/Cronjobs/currencies_update_yahoo.php

# manage the monthly services subscription
0 6 1 * * php /usr/lib/a2billing/Cronjobs/a2billing_subscription_fee.php

# To check account of each Users and send an email if the balance is
# less than the user have choice.
0 * * * * php /usr/lib/a2billing/Cronjobs/a2billing_notify_account.php

# this script will browse all the DID that are reserve and check if
# the customer need to pay for it
# bill them or warn them per email to know if they want to pay in
# order to keep their DIDs
0 2 * * * php /usr/lib/a2billing/Cronjobs/a2billing_bill_diduse.php

# This script will take care of the recurring service.
0 12 * * * php /usr/lib/a2billing/Cronjobs/a2billing_batch_process.php

#Generate Invoices at 6am everyday
0 6 * * * php /usr/lib/a2billing/Cronjobs/a2billing_batch_billing.php

# to proceed the autodialer
*/5 * * * * php /usr/lib/a2billing/Cronjobs/a2billing_batch_autodialer.php

# manage alarms
0 * * * * php /usr/lib/a2billing/Cronjobs/a2billing_alarm.php
" >>  /etc/cron.d/a2billing

echo "+----------------------------------------------------------------+"
echo "| creando archivos SIP y IAX                                     |"
echo "+----------------------------------------------------------------+"

cd /etc/asterisk/
touch additional_a2billing_iax.conf
touch additional_a2billing_sip.conf
touch extensions_a2billing.conf

chown asterisk:asterisk additional_a2billing_iax.conf
chown asterisk:asterisk additional_a2billing_sip.conf
chown asterisk:asterisk extensions_a2billing.conf

echo "#include additional_a2billing_sip.conf" >> /etc/asterisk/sip_custom.conf
echo "#include additional_a2billing_iax.conf" >> /etc/asterisk/iax_custom.conf
echo "#include extensions_a2billing.conf" >> /etc/asterisk/extensions_custom.conf

echo "[a2billing]
include => a2billing_callingcard
include => a2billing_monitoring
include => a2billing_voucher

[a2billing_callingcard]
; CallingCard application
exten => _XXXX.,1,Answer
exten => _XXXX.,2,Wait,2
exten => _XXXX.,3,DeadAGI,a2billing.php
exten => _XXXX.,4,Wait,2
exten => _XXXX.,5,Hangup

[a2billing_monitoring]
; Monitoring IVR application
exten => 100,1,Answer
exten => 100,2,Wait,2
exten => 100,3,DeadAGI,a2billing_monitoring.php
exten => 100,4,Wait,2
exten => 100,5,Hangup

[a2billing_voucher]
exten => 101,1,Answer
exten => 101,2,Wait,2
exten => 101,3,DeadAGI(a2billing.php|1|voucher)
exten => 101,4,Wait,2
exten => 101,5,Hangup

[a2billing_did]
; CallingCard DID application
exten => _X.,1,DeadAGI(a2billing.php|1|did)
" >> /etc/asterisk/extensions_a2billing.conf

echo "+----------------------------------------------------------------+"
echo "| Configurando Asterisk Manager                                  |"
echo "+----------------------------------------------------------------+"

echo "
[${A2BILLING_MGR}]
secret = ${A2BILLING_MGR_PW}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
read = system,call,log,verbose,command,agent,user
write = system,call,log,verbose,command,agent,user
" >> /etc/asterisk/manager_custom.conf

echo "+----------------------------------------------------------------+"
echo "| Instalación de Sound                                           |"
echo "+----------------------------------------------------------------+"

sed -i "s/\(ast_sound=*\)\(.*\)/\1\/var\/lib\/asterisk\/sounds/" /usr/src/a2billing/addons/sounds/install_a2b_sounds_deb.sh
/usr/src/a2billing/addons/sounds/install_a2b_sounds_deb.sh
chown -R asterisk:asterisk /var/lib/asterisk/sounds/

mkdir -p /var/lib/asterisk/mohmp3/acc_1
mkdir -p /var/lib/asterisk/mohmp3/acc_2
mkdir -p /var/lib/asterisk/mohmp3/acc_3
mkdir -p /var/lib/asterisk/mohmp3/acc_4
mkdir -p /var/lib/asterisk/mohmp3/acc_5
mkdir -p /var/lib/asterisk/mohmp3/acc_6
mkdir -p /var/lib/asterisk/mohmp3/acc_7
mkdir -p /var/lib/asterisk/mohmp3/acc_8
mkdir -p /var/lib/asterisk/mohmp3/acc_9
mkdir -p /var/lib/asterisk/mohmp3/acc_10
chmod -R 777 /var/lib/asterisk/mohmp3/acc_*
chown -R asterisk:asterisk /var/lib/asterisk/mohmp3/

echo "
; class definitions for a2billing
acc_1 => mp3:/var/lib/asterisk/mohmp3/acc_1
acc_2 => mp3:/var/lib/asterisk/mohmp3/acc_2
acc_3 => mp3:/var/lib/asterisk/mohmp3/acc_3
acc_4 => mp3:/var/lib/asterisk/mohmp3/acc_4
acc_5 => mp3:/var/lib/asterisk/mohmp3/acc_5
acc_6 => mp3:/var/lib/asterisk/mohmp3/acc_6
acc_7 => mp3:/var/lib/asterisk/mohmp3/acc_7
acc_8 => mp3:/var/lib/asterisk/mohmp3/acc_8
acc_9 => mp3:/var/lib/asterisk/mohmp3/acc_9
acc_10 => mp3:/var/lib/asterisk/mohmp3/acc_10
" >> /etc/asterisk/musiconhold_custom.conf

echo "+----------------------------------------------------------------+"
echo "| Instalando componentes AGI                                     |"
echo "+----------------------------------------------------------------+"

cp /usr/src/a2billing/AGI/a2billing.php /var/lib/asterisk/agi-bin/
cp -rf /usr/src/a2billing/common/lib /var/lib/asterisk/agi-bin/
chmod +x /var/lib/asterisk/agi-bin/a2billing.php
chown -R asterisk:asterisk /var/lib/asterisk/agi-bin

echo "+----------------------------------------------------------------+"
echo "| Call back daemon (only for Call backs)                         |"
echo "+----------------------------------------------------------------+"

cd /usr/src/a2billing/CallBack
easy_install callback-daemon-py/dist/callback_daemon-1.0.prod_r1527-py2.5.egg

cd /usr/src/a2billing/CallBack/callback-daemon-py/callback_daemon/
cp a2b-callback-daemon.debian /etc/init.d/a2b-callback-daemon
chmod +x /etc/init.d/a2b-callback-daemon

update-rc.d a2b-callback-daemon defaults 40 603
mkdir -p /var/lib/asterisk/mohmp3/acc_7
mkdir -p /var/lib/asterisk/mohmp3/acc_8
mkdir -p /var/lib/asterisk/mohmp3/acc_9
mkdir -p /var/lib/asterisk/mohmp3/acc_10
chmod -R 777 /var/lib/asterisk/mohmp3/acc_*
chown -R asterisk:asterisk /var/lib/asterisk/mohmp3/

echo "
; class definitions for a2billing
acc_1 => mp3:/var/lib/asterisk/mohmp3/acc_1
acc_2 => mp3:/var/lib/asterisk/mohmp3/acc_2
acc_3 => mp3:/var/lib/asterisk/mohmp3/acc_3
acc_4 => mp3:/var/lib/asterisk/mohmp3/acc_4
acc_5 => mp3:/var/lib/asterisk/mohmp3/acc_5
acc_6 => mp3:/var/lib/asterisk/mohmp3/acc_6
acc_7 => mp3:/var/lib/asterisk/mohmp3/acc_7
acc_8 => mp3:/var/lib/asterisk/mohmp3/acc_8
acc_9 => mp3:/var/lib/asterisk/mohmp3/acc_9
acc_10 => mp3:/var/lib/asterisk/mohmp3/acc_10
" >> /etc/asterisk/musiconhold_custom.conf

echo "+----------------------------------------------------------------+"
echo "| Instalando componentes AGI                                     |"
echo "+----------------------------------------------------------------+"

cd /usr/src/a2billing/AGI
cp a2billing.php /var/lib/asterisk/agi-bin/
cp a2billing-monitoring.php /var/lib/asterisk/agi-bin/
cp -Rf lib /var/lib/asterisk/agi-bin/
chmod +x /var/lib/asterisk/agi-bin/a2billing.php
chmod +x /var/lib/asterisk/agi-bin/a2billing-monitoring.php
chown -R asterisk:asterisk /var/lib/asterisk/agi-bin

echo "+----------------------------------------------------------------+"
echo "| Call back daemon (only for Call backs)                         |"
echo "+----------------------------------------------------------------+"

easy_install /usr/src/a2billing/CallBack/callback-daemon-py/dist/callback_daemon-*.egg

cd /usr/src/a2billing/CallBack/callback-daemon-py/callback_daemon
cp a2b-callback-daemon.debian /etc/init.d/a2b-callback-daemon
chmod +x /etc/init.d/a2b-callback-daemon

update-rc.d a2b-callback-daemon defaults 40 60
/etc/init.d/a2b-callback-daemon start

echo "+----------------------------------------------------------------+"
echo "| Instalation succesfull                                         |"
echo "+----------------------------------------------------------------+"
