#!/bin/bash             
#                       
# debpbx-help - 31/07/2010 
#                       
# DebPBX-1.3.0        
# Author: Federico Pereira <info@opentecnologic.com> & <fpereira@debpbx.org>
# Copyright 2008 Federico Pereira (LordBaseX)       
# This script is licensed under GNU GPL version 2.0 
#                                                   
clear

cat<<EOF

DebPBX HELP

Commands               Descriptions
-----------------------------------------------------------------------
asterisk -r            Asterisk CLI.
passwd                 set root password for console login.
debpbx-cisco           create a SIPDefault.cnf in /tftpboot.
debpbx-pstn	       detect and setup supported PSTN interface cards.
debpbx-update	       System to update debpbx.
debpbx-password        Change all key system.
debpbx-chan_skype      Official integration of Skype for asterisk.
debpbx-siptosis        Autoinstall SipToSis of Skype integration through X and Java.
debpbx-a2billing       Instalation a2billing 
debpbx-festival        Instalation festival
debpbx-fop2	       Integracion fop2
debpbx-wizard          Wizard (Password root, edit host and hostname, change mail admin from /etc/aliases) 
EOF
